# Generated by Django 4.2 on 2023-05-03 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(max_length=100, null=True, verbose_name='Номер телефона'),
        ),
    ]
